local _, T = ...
T[3] = {
    ["Basic Campfire"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 100, --Recipe cost in copper
        materials = {"Simple Wood"},
        materialsNumber = {1},
    },
    ["Crispy Bat Wing"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "Recipe: Crispy Bat Wing",
		cost = 24,
        materials = {"Meaty Bat Wing", "Mild Spices"},
        materialsNumber = {1, 1},
    },
    ["Herb Baked Egg"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 0,
        materials = {"Small Egg", "Mild Spices"},
        materialsNumber = {1, 1},
    },
    ["Brilliant Smallfish"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 40,
        materials = {"Raw Brilliant Smallfish"},
        materialsNumber = {1},
    },
    ["Slitherskin Mackerel"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 40, 
        materials = {"Raw Slitherskin Mackerel"},
        materialsNumber = {1},
    },
    ["Roasted Boar Meat"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 0, 
        materials = {"Chunk of Boar Meat"},
        materialsNumber = {1},
    },
    ["Charred Wolf Meat"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 0, 
        materials = {"Stringy Wolf Meat"},
        materialsNumber = {1},
    },
}