local _, T = ...
T[3] = {
    ["Basic Campfire"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 100, --Recipe cost in copper
		vendor = 0,
        materials = {"Simple Wood"},
        materialsNumber = {1},
    },
    ["Crispy Bat Wing"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "Recipe: Crispy Bat Wing",
		cost = 24,
		vendor = 10,
        materials = {"Meaty Bat Wing", "Mild Spices"},
        materialsNumber = {1, 1},
    },
    ["Herb Baked Egg"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 0,
		vendor = 10,
        materials = {"Small Egg", "Mild Spices"},
        materialsNumber = {1, 1},
    },
    ["Brilliant Smallfish"] = {
        trainableLevel = 1,
        yellowLevel = 45,
        greyLevel = 85,
		recipe = "None",
		cost = 40,
		vendor = 1,
        materials = {"Raw Brilliant Smallfish"},
        materialsNumber = {1},
    },
    ["Slitherskin Mackerel"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 40, 
		vendor = 1,
        materials = {"Raw Slitherskin Mackerel"},
        materialsNumber = {1},
    },
    ["Roasted Boar Meat"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 0, 
		vendor = 6,
        materials = {"Chunk of Boar Meat"},
        materialsNumber = {1},
    },
    ["Charred Wolf Meat"] = {
        trainableLevel = 1,
        yellowLevel =45,
        greyLevel = 85,
		recipe = "None",
		cost = 0, 
		vendor = 5,
        materials = {"Stringy Wolf Meat"},
        materialsNumber = {1},
    },
    ["Kaldorei Spider Kabob"] = {
        trainableLevel = 10,
        yellowLevel = 50,
        greyLevel = 90,
        recipe = "Recipe: Kaldorei Spider Kabob",
        cost = -1,
        vendor = 10,
        materials = {"Small Spider Leg"},
        materialsNumber = {"1"},
    },
    ["Spiced Wolf Meat"] = {
        trainableLevel = 10,
        yellowLevel = 50,
        greyLevel = 90,
        recipe = "None",
        cost = 50,
        vendor = 10,
        materials = {"Stringy Wolf Meat", "Mild Spices"},
        materialsNumber = {"1", "1"},
    },
    ["Scorpid Surprise"] = {
        trainableLevel = 20,
        yellowLevel = 60,
        greyLevel = 100,
        recipe = "Recipe: Scorpid Surprise",
        cost = 126,
        vendor = 10,
        materials = {"Scorpid Stinger"},
        materialsNumber = {"1"},
    },
    ["Beer Basted Boar Ribs"] = {
        trainableLevel = 25,
        yellowLevel = 60,
        greyLevel = 100,
        recipe = "Recipe: Beer Basted Boar Ribs",
        cost = -1,
        vendor = 10,
        materials = {"Crag Boar Rib", "Rhapsody Malt"},
        materialsNumber = {"1", "1"},
    },
    ["Egg Nog"] = {
        trainableLevel = 35,
        yellowLevel = 75,
        greyLevel = 115,
        recipe = "Recipe: Egg Nog",
        cost = 240,
        vendor = 9,
        materials = {"Small Egg", "Ice Cold Milk", "Holiday Spirits", "Holiday Spices"},
        materialsNumber = {"1", "1", "1", "1"},
    },
    ["Roasted Kodo Meat"] = {
        trainableLevel = 35,
        yellowLevel = 75,
        greyLevel = 115,
        recipe = "Recipe: Roasted Kodo Meat",
        cost = 216,
        vendor = 18,
        materials = {"Kodo Meat", "Mild Spices"},
        materialsNumber = {"1", "1"},
    },
    ["Smoked Bear Meat"] = {
        trainableLevel = 40,
        yellowLevel = 80,
        greyLevel = 120,
        recipe = "Recipe: Smoked Bear Meat",
        cost = 230,
        vendor = 6,
        materials = {"Bear Meat"},
        materialsNumber = {"1"},
    },
    ["Boiled Clams"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "None",
        cost = 100,
        vendor = 20,
        materials = {"Clam Meat", "Refreshing Spring Water"},
        materialsNumber = {"1", "1"},
    },
    ["Coyote Steak"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "None",
        cost = 100,
        vendor = 20,
        materials = {"Coyote Meat"},
        materialsNumber = {"1"},
    },
    ["Fillet of Frenzy"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Fillet of Frenzy",
        cost = 378,
        vendor = 6,
        materials = {"Soft Frenzy Fish", "Mild Spices"},
        materialsNumber = {"1", "1"},
    },
    ["Goretusk Liver Pie"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Goretusk Liver Pie",
        cost = -1,
        vendor = 25,
        materials = {"Goretusk Liver", "Mild Spices"},
        materialsNumber = {"1", "1"},
    },
    ["Loch Frenzy Delight"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Loch Frenzy Delight",
        cost = 360,
        vendor = 3,
        materials = {"Raw Loch Frenzy", "Mild Spices"},
        materialsNumber = {"1", "1"},
    },
    ["Longjaw Mud Snapper"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Longjaw Mud Snapper",
        cost = 400,
        vendor = 1,
        materials = {"Raw Longjaw Mud Snapper"},
        materialsNumber = {"1"},
    },
    ["Rainbow Fin Albacore"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Rainbow Fin Albacore",
        cost = 400,
        vendor = 3,
        materials = {"Raw Rainbow Fin Albacore"},
        materialsNumber = {"1"},
    },
    ["Strider Stew"] = {
        trainableLevel = 50,
        yellowLevel = 90,
        greyLevel = 130,
        recipe = "Recipe: Strider Stew",
        cost = -1,
        vendor = 36,
        materials = {"Strider Meat", "Shiny Red Apple"},
        materialsNumber = {"1", "1"},
    },
    ["Blood Sausage"] = {
        trainableLevel = 60,
        yellowLevel = 100,
        greyLevel = 140,
        recipe = "Recipe: Blood Sausage",
        cost = -1,
        vendor = 80,
        materials = {"Bear Meat", "Boar Intestines", "Spider Ichor"},
        materialsNumber = {"1", "1", "1"},
    },
    ["Thistle Tea"] = {
        trainableLevel = 60,
        yellowLevel = 100,
        greyLevel = 140,
        recipe = "Recipe: Thistle Tea",
        cost = -1,
        vendor = 30,
        materials = {"Swiftthistle", "Refreshing Spring Water"},
        materialsNumber = {"1", "1"},
    },
}